/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nlopt;

public class ForcedStopException extends java.lang.RuntimeException {
    public ForcedStopException(String message) {
      super(message);
    }
  
}
