/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nlopt;

public class NLopt {
  public static void srand(long seed) {
    NLoptJNI.srand(seed);
  }

  public static void srandTime() {
    NLoptJNI.srandTime();
  }

  public static int versionMajor() {
    return NLoptJNI.versionMajor();
  }

  public static int versionMinor() {
    return NLoptJNI.versionMinor();
  }

  public static int versionBugfix() {
    return NLoptJNI.versionBugfix();
  }

  public static String algorithmName(Algorithm a) {
    return NLoptJNI.algorithmName(a.swigValue());
  }

}
