/****************************************************************************

    PacPMA - the PAC-based Parametric Model Analyzer
    Copyright (C) 2023

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 *****************************************************************************/

package pacpma.algebra.polynomial;

import java.math.BigDecimal;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import pacpma.algebra.Variable;

/**
 * A class representing a polynomial.
 * 
 * @author Andrea Turrini
 *
 */
public class Polynomial {
    private final int maximumDegree;
    private final Map<Integer, Collection<Monomial>> monomials;

    /**
     * Generates a complete polynomial over the variables defined in
     * {@link Variable}, where the monomials in the polynomial have degree at most
     * {@code maximumDegree}.
     * 
     * @param maximumDegree
     *            the maximum degree of this polynomial
     */
    public Polynomial(int maximumDegree) {
        this.maximumDegree = maximumDegree;
        this.monomials = new HashMap<>();
        
        Monomial.initializeMonomial(Variable.getVariables());

        Collection<Monomial> cm = new HashSet<Monomial>();
        cm.add(Monomial.getZeroDegreeMonomial());
        monomials.put(0, cm);

        for (int currentDegree = 1; currentDegree <= maximumDegree; currentDegree++) {
            Collection<Monomial> currentDegreeMonomials = new HashSet<>();
            Collection<Monomial> previousDegreeMonomials = monomials.get(currentDegree - 1);
            for (Variable v : Variable.getVariables()) {
                for (Monomial m : previousDegreeMonomials) {
                    currentDegreeMonomials.add(Monomial.increaseDegree(m, v));
                }
            }
            monomials.put(currentDegree, currentDegreeMonomials);
        }
    }
    
    /**
     * Provides the list of coefficients of all monomials in this polynomial, as
     * generated by {@link Monomial#getNamedCoefficient()}.
     * 
     * @return the list of coefficients
     */
    public List<String> getCoefficients() {
        List<String> coefficients = new LinkedList<>();
        monomials.values().forEach(
                mons -> mons.forEach(
                        monomial -> coefficients.add(monomial.getNamedCoefficient())
                )
        );
        return coefficients;
    }

    /**
     * Evaluates the monomials in this polynomial with respect to the given value of
     * the variables.
     * 
     * @param values
     *            the values of the variables
     * @return a {@link Map} assigning to each
     *         {@link Monomial#getNamedCoefficient()} its evaluation
     *         {@link Monomial#evaluate(Map)}
     */
    public Map<String, BigDecimal> evaluate(Map<Variable, BigDecimal> values) {
        Map<String, BigDecimal> coefficients = new HashMap<>();
        monomials.values().forEach(
                mons -> mons.forEach(
                        monomial -> coefficients.put(monomial.getNamedCoefficient(), monomial.evaluate(values))
                )
        );
        return coefficients;
    }
    
    /**
     * Generates a LaTeX expression for this polynomial, with coefficients for the
     * monomials taken from {@code coefficientValues}.
     * 
     * @param coefficientValues
     *            the values associated to the coefficients
     *            {@link Monomial#getNamedCoefficient()} of the monomials
     * @return a LaTeX expression representing this polynomial
     */
    public String getLatexExpression(Map<String, BigDecimal> coefficientValues) {
        StringBuilder sb = new StringBuilder();
        sb.append(coefficientValues.get(Monomial.getZeroDegreeMonomial().getNamedCoefficient()));
        for (int degree = 1; degree <= maximumDegree; degree++) {
            for (Monomial monomial : monomials.get(degree)) {
                BigDecimal value = coefficientValues.get(monomial.getNamedCoefficient());
                assert value != null;
                if (value.compareTo(BigDecimal.ZERO) >= 0) {
                    sb.append(" + ");
                } else {
                    sb.append(" - ");
                }
                sb.append(value.abs().toPlainString()).append(" \\cdot ").append(monomial.getLatexExpression());
            }
        }
        return sb.toString();
    }
    
    /**
     * Generates a mathematical expression for this polynomial, with coefficients
     * for the monomials taken from {@code coefficientValues}.
     * 
     * @param coefficientValues
     *            the values associated to the coefficients
     *            {@link Monomial#getNamedCoefficient()} of the monomials
     * @return a mathematical expression representing this polynomial
     */
    public String getMathExpression(Map<String, BigDecimal> coefficientValues) {
        StringBuilder sb = new StringBuilder();
        sb.append(coefficientValues.get(Monomial.getZeroDegreeMonomial().getNamedCoefficient()));
        for (int degree = 1; degree <= maximumDegree; degree++) {
            for (Monomial monomial : monomials.get(degree)) {
                BigDecimal value = coefficientValues.get(monomial.getNamedCoefficient());
                assert value != null;
                if (value.compareTo(BigDecimal.ZERO) >= 0) {
                    sb.append(" + ");
                } else {
                    sb.append(" - ");
                }
                sb.append(value.abs().toPlainString()).append(" * ").append(monomial.getMathExpression());
            }
        }
        return sb.toString();
    }
    
    /**
     * Generates a MATLAB expression for this polynomial, with coefficients
     * for the monomials taken from {@code coefficientValues}.
     * 
     * @param coefficientValues
     *            the values associated to the coefficients
     *            {@link Monomial#getNamedCoefficient()} of the monomials
     * @return a mathematical expression representing this polynomial
     */
    public String getMatlabExpression(Map<String, BigDecimal> coefficientValues) {
        StringBuilder sb = new StringBuilder();
        sb.append(coefficientValues.get(Monomial.getZeroDegreeMonomial().getNamedCoefficient()));
        for (int degree = 1; degree <= maximumDegree; degree++) {
            for (Monomial monomial : monomials.get(degree)) {
                BigDecimal value = coefficientValues.get(monomial.getNamedCoefficient());
                assert value != null;
                if (value.compareTo(BigDecimal.ZERO) >= 0) {
                    sb.append(" + ");
                } else {
                    sb.append(" - ");
                }
                sb.append(value.abs().toPlainString()).append(" * ").append(monomial.getMatlabExpression());
            }
        }
        return sb.toString();
    }
}
